apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-resource-quota
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "500Mi"
    limits.cpu: "1400m"
    limits.memory: "3500Mi"
    pods: "7"