# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: k8s-hatchery
    
steps:
- script: |
    curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    az login
  displayName: 'install az'

- script: |
    wget -O- https://apt.releases.hashicorp.com/gpg | \
    gpg --dearmor | \
    sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
    gpg --no-default-keyring \
    --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
    --fingerprint
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
    https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
    sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt update
    sudo apt-get install terraform
    terraform init --upgrade
    terraform apply
  displayName: 'Install and initialize Terraform'
  workingDirectory: ./gitops/terraform/

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Unicorn MS Academy ARCH 11(ccf6dd5f-428b-4601-bec7-8a6b42520dc9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --name k8s_vanek-aks --resource-group k8s_vanek-rg
      az aks update -n k8s_vanek-aks -g k8s_vanek-rg --attach-acr vanekCR
- task: Docker@2
  inputs:
    containerRegistry: 'vanek-k8s'
    
- script: |
    kubectl create ns dev
    kubectl apply -k ./gitops/k8s/base
  displayName: 'run kustomize'