# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: k8s-hatchery
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      name: k8s-hatchery
    steps:
    - task: CmdLine@2
      displayName: 'install az'
      inputs:
        script: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
    - task: AzureCLI@2
      displayName: 'Install, init, apply terraform, AKS credentials'
      inputs:
        azureSubscription: 'Unicorn MS Academy ARCH 11(ccf6dd5f-428b-4601-bec7-8a6b42520dc9)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          wget -O- https://apt.releases.hashicorp.com/gpg | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          gpg --no-default-keyring \
          --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg \
          --fingerprint
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] \
          https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
          sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt-get install terraform
          terraform init --upgrade
          terraform apply -var="client_secret=$(CLIENT_SECRET)" -var="tenant_id=$(TENANT_ID)" -var="client_id=$(CLIENT_ID)" -var="subscription_id=$(SUBSCRIPTION_ID)" -auto-approve
          
          az aks get-credentials --name k8s_vanek-aks --resource-group k8s_vanek-rg --admin
          az aks update -n k8s_vanek-aks -g k8s_vanek-rg --attach-acr "/subscriptions/ccf6dd5f-428b-4601-bec7-8a6b42520dc9/resourceGroups/k8s_vanek-rg/providers/Microsoft.ContainerRegistry/registries/vanekCR"
        workingDirectory: 'gitops/terraform/'
        
    - task: Docker@2
      displayName: 'docker build and push'
      inputs:
        containerRegistry: 'az-vanek-sc1'
        repository: 'vanekcr.azurecr.io/vanekapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: 'latest'

    
    - task: CmdLine@2
      displayName: 'run kustomize'
      inputs:
        script: |
          kubectl create ns dev
          kubectl create secret docker-registry --name vanekapp --namespace dev --docker-server=vanekcr.azurecr.io --docker-username=$(CLIENT_ID) from previous step> --docker-password=$(CLIENT_SECRET)
          kubectl apply -k ./gitops/k8s/base

