kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - "../base"

namespace: alysina-dev

replicas:
  - name: uni-academy
    count: 1

images:
  - name: acruniacademy.azurecr.io/uni-academy
    newTag: 1.0.0-dev

patches:
  - path: './config.patch.yaml'
    target:
      kind: ConfigMap
      name: uni-academy
  # TODO: fix
  # - patch: './ingress.patch.yaml'
  #   target:
  #     kind: Ingress
  #     name: uni-academy