kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

bases:
  - "../base"

namespace: dev

replicas:
  - name: vanekapp
    count: 3

images:
  - name: vanekcr.azurecr.io/vanekapp
  - newTag: latest

patches:
  - patch: "./ingress.patch.yaml"
    target:
      kind: Ingress
      name: vanekapp
